version: '3'

services:
  med_notes_api:
    build: .
    restart: always
    ports:
      - 8082:8082
    networks:
      - springapi-net
    environment:
      - spring.data.mongodb.uri="mongodb://root:secret@mongodb:27017/mydatabase"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27016:27017
    networks:
      - springapi-net
    volumes:
      - mongodb_data:/data/db
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'

volumes:
  mongodb_data:

networks:
  springapi-net:
